### ISSUE TITLE
Adding mentors to GSoC organisation page

### ISSUE THREAD

**Issue by dicook** [rstats-gsoc/gsoc2023#1]
Hi @tdhock Would you be able to add Mitch O'Hara-Wild to the mentors for the "R project for statistical computing"? As of now, when he logs in to GSoC he doesn't have any option to accept the program rules for this year.

**Comment by tdhock** [comment]
Sure; I invited mail@mitchelloharawild.com

**Comment by dvats** [comment]
Could I request the admin to add me as a mentor as well: dootika@iitk.ac.in
And James Flegal: jflegal@ucr.edu

**Comment by tdhock** [comment]
ok I invited them, did that work?

**Comment by dvats** [comment]
Yep, that worked for me. Most likely worked for James as well, and I'll ping here again if there is an issue. Thanks
